[__config__]
oldver = "versions.json"
newver = "versions_new.json"
max_concurrency = 4

[attica]
source = "archpkg"
strip_release = true

[automake]
source = "archpkg"
strip_release = true

[autoconf]
source = "archpkg"
strip_release = true

[bash]
source = "repology"
repo = "distrowatch"

[bc]
source = "github"
github = "gavinhoward/bc"
use_latest_release = true

[bison]
source = "repology"
repo = "debian_unstable"

[bzip2]
source = "archpkg"
strip_release = true

[cairo]
source = "archpkg"
strip_release = true

[check]
source = "archpkg"
strip_release = true

[cmake]
source = "archpkg"
strip_release = true

[curl]
source = "archpkg"
strip_release = true

[dash]
source = "archpkg"
strip_release = true

[dbus]
source = "archpkg"
strip_release = true

[diffutils]
source = "archpkg"
strip_release = true

[e2fsprogs]
source = "archpkg"
strip_release = true

[extra-cmake-modules]
source = "archpkg"
strip_release = true

[expat]
source = "archpkg"
strip_release = true

# TODO: check latest RC
#[finit]
#source = "github"
#github = "troglobit/finit"
#use_latest_release = false

[flex]
source = "archpkg"
strip_release = true

# TODO: using beta version
#[fontconfig]
#source = "repology"
#repo = "debian_unstable"

[freetype]
source = "archpkg"
archpkg = "freetype2"
strip_release = true

[fribidi]
source = "archpkg"
strip_release = true

[gettext-tiny]
source = "repology"
repo = "alpine_edge"

[git]
source = "archpkg"
strip_release = true

[glib]
source = "archpkg"
archpkg = "glib2"
strip_release = true

# TODO: custom pkg_url
#[go]
#source = "archpkg"
#strip_release = true

[gperf]
source = "archpkg"
strip_release = true

[grep]
source = "archpkg"
strip_release = true

[harfbuzz]
source = "archpkg"
strip_release = true

[json-c]
source = "archpkg"
strip_release = true

[jsoncpp]
source = "archpkg"
strip_release = true

[karchive]
source = "archpkg"
strip_release = true

[kconfig]
source = "archpkg"
strip_release = true

[kcoreaddons]
source = "archpkg"
strip_release = true

[kwidgetsaddons]
source = "archpkg"
strip_release = true

[less]
source = "archpkg"
strip_release = true

[libarchive]
source = "archpkg"
strip_release = true

[libdrm]
source = "archpkg"
strip_release = true

# TODO: 20191231-3.1 vs 20191231.3.1
#[libedit]
#source = "repology"
#repo = "arch"

[libepoxy]
source = "archpkg"
strip_release = true

[libevdev]
source = "archpkg"
strip_release = true

[libevent]
source = "archpkg"
strip_release = true

[libffi]
source = "archpkg"
strip_release = true

[libinput]
source = "archpkg"
strip_release = true

[libite]
source = "repology"
repo = "debian_unstable"

[libjpeg-turbo]
source = "archpkg"
strip_release = true

[libpng]
source = "archpkg"
strip_release = true

[libseccomp]
source = "archpkg"
strip_release = true

[libucontext]
source = "repology"
repo = "alpine_edge"

[libudev-zero]
source = "repology"
repo = "kiss_main"

[libuev]
source = "repology"
repo = "void_x86_64"

[liburing]
source = "archpkg"
strip_release = true

[libusb]
source = "archpkg"
strip_release = true

[libuuid]
source = "repology"
repo = "gentoo"

[libuv]
source = "archpkg"
strip_release = true

[libxkbcommon]
source = "archpkg"
strip_release = true

# TODO: check kernel.org
#[linux]
#source = "repology"
#repo = "void_x86_64"

# TODO: intentionally using non-latest version
#[linux-headers]
#source = "repology"
#repo = "alpine_edge"

[llvm]
source = "archpkg"
strip_release = true

[m4]
source = "archpkg"
strip_release = true

[make]
source = "archpkg"
strip_release = true

[mako]
source = "pypi"

[markupsafe]
source = "pypi"

[mawk]
source = "repology"
repo = "kiss_community"

[mc]
source = "archpkg"
strip_release = true

[mesa]
source = "archpkg"
strip_release = true

[meson]
source = "archpkg"
strip_release = true

[mtdev]
source = "archpkg"
strip_release = true

[musl]
source = "archpkg"
strip_release = true

[ncurses]
source = "archpkg"
strip_release = true

[nghttp2]
source = "repology"
repo = "void_x86_64"

[ninja]
source = "archpkg"
strip_release = true

[openssl]
source = "repology"
repo = "distrowatch"

[pango]
source = "archpkg"
strip_release = true

[pcre]
source = "archpkg"
strip_release = true

[pcre2]
source = "archpkg"
strip_release = true

[perl]
source = "archpkg"
strip_release = true

[phonon]
source = "repology"
repo = "arch"

[pigz]
source = "archpkg"
strip_release = true

[pixman]
source = "archpkg"
strip_release = true

[pkgconf]
source = "archpkg"
strip_release = true

[plasma-wayland-protocols]
source = "archpkg"
strip_release = true

[pyparsing]
source = "pypi"

[python]
source = "archpkg"
strip_release = true

[qemu]
source = "archpkg"
strip_release = true

[qt6]
source = "archpkg"
archpkg = "qt6-base"
strip_release = true

[rhash]
source = "archpkg"
strip_release = true

[rsync]
source = "archpkg"
strip_release = true

[ruby]
source = "repology"
repo = "distrowatch"

[seatd]
source = "repology"
repo = "kiss_community"

[setuptools]
source = "pypi"
pypi = "setuptools"

[slang]
source = "archpkg"
strip_release = true

[six]
source = "pypi"

[solid]
source = "archpkg"
strip_release = true

[sonnet]
source = "archpkg"
strip_release = true

[spice]
source = "archpkg"
strip_release = true

[spice-protocol]
source = "archpkg"
strip_release = true

# TODO: 3340100 vs 3.34.1
#[sqlite]
#source = "archpkg"
#strip_release = true

[strace]
source = "archpkg"
strip_release = true

[sway]
source = "archpkg"
strip_release = true

[tmux]
source = "repology"
repo = "debian_unstable"

[toybox]
source = "repology"
repo = "alpine_edge"

[usbredir]
source = "archpkg"
strip_release = true

[valgrind]
source = "archpkg"
strip_release = true

[wayland]
source = "archpkg"
strip_release = true

[wayland-protocols]
source = "archpkg"
strip_release = true

[wget]
source = "archpkg"
strip_release = true

[wlroots]
source = "archpkg"
strip_release = true

[xkeyboard-config]
source = "archpkg"
strip_release = true

[xz]
source = "archpkg"
strip_release = true

[zlib]
source = "archpkg"
strip_release = true

[zstd]
source = "archpkg"
strip_release = true
